# DBSCAN Clustering

In [1]:
#Crime Data DBSCAN Clustering

In [2]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

C:\Users\theam\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [3]:
crime_data = pd.read_csv("C:\\ExcelR\Data Science Assignments\\7-Clustering\\crime_data.csv")
crime_data.head()

Unnamed: 0  Murder  Assault  UrbanPop  Rape
0     Alabama    13.2      236        58  21.2
1      Alaska    10.0      263        48  44.5
2     Arizona     8.1      294        80  31.0
3    Arkansas     8.8      190        50  19.5
4  California     9.0      276        91  40.6

In [4]:
df = crime_data.drop(['Unnamed: 0'],axis=1)

In [5]:
array=df.values
array

array([[ 13.2, 236. ,  58. ,  21.2],
       [ 10. , 263. ,  48. ,  44.5],
       [  8.1, 294. ,  80. ,  31. ],
       [  8.8, 190. ,  50. ,  19.5],
       [  9. , 276. ,  91. ,  40.6],
       [  7.9, 204. ,  78. ,  38.7],
       [  3.3, 110. ,  77. ,  11.1],
       [  5.9, 238. ,  72. ,  15.8],
       [ 15.4, 335. ,  80. ,  31.9],
       [ 17.4, 211. ,  60. ,  25.8],
       [  5.3,  46. ,  83. ,  20.2],
       [  2.6, 120. ,  54. ,  14.2],
       [ 10.4, 249. ,  83. ,  24. ],
       [  7.2, 113. ,  65. ,  21. ],
       [  2.2,  56. ,  57. ,  11.3],
       [  6. , 115. ,  66. ,  18. ],
       [  9.7, 109. ,  52. ,  16.3],
       [ 15.4, 249. ,  66. ,  22.2],
       [  2.1,  83. ,  51. ,   7.8],
       [ 11.3, 300. ,  67. ,  27.8],
       [  4.4, 149. ,  85. ,  16.3],
       [ 12.1, 255. ,  74. ,  35.1],
       [  2.7,  72. ,  66. ,  14.9],
       [ 16.1, 259. ,  44. ,  17.1],
       [  9. , 178. ,  70. ,  28.2],
       [  6. , 109. ,  53. ,  16.4],
       [  4.3, 102. ,  62. ,  16.5],
 

In [6]:
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler

C:\Users\theam\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [7]:
stscaler = StandardScaler().fit(array)
scaled_crime_data = stscaler.transform(array) 
scaled_crime_data

array([[ 1.25517927,  0.79078716, -0.52619514, -0.00345116],
       [ 0.51301858,  1.11805959, -1.22406668,  2.50942392],
       [ 0.07236067,  1.49381682,  1.00912225,  1.05346626],
       [ 0.23470832,  0.23321191, -1.08449238, -0.18679398],
       [ 0.28109336,  1.2756352 ,  1.77678094,  2.08881393],
       [ 0.02597562,  0.40290872,  0.86954794,  1.88390137],
       [-1.04088037, -0.73648418,  0.79976079, -1.09272319],
       [-0.43787481,  0.81502956,  0.45082502, -0.58583422],
       [ 1.76541475,  1.99078607,  1.00912225,  1.1505301 ],
       [ 2.22926518,  0.48775713, -0.38662083,  0.49265293],
       [-0.57702994, -1.51224105,  1.21848371, -0.11129987],
       [-1.20322802, -0.61527217, -0.80534376, -0.75839217],
       [ 0.60578867,  0.94836277,  1.21848371,  0.29852525],
       [-0.13637203, -0.70012057, -0.03768506, -0.0250209 ],
       [-1.29599811, -1.39102904, -0.5959823 , -1.07115345],
       [-0.41468229, -0.67587817,  0.03210209, -0.34856705],
       [ 0.44344101, -0.

In [11]:
dbscan = DBSCAN(eps=1, min_samples=5)
dbscan.fit(scaled_crime_data)

DBSCAN(algorithm='auto', eps=1, leaf_size=30, metric='euclidean',
       metric_params=None, min_samples=5, n_jobs=None, p=None)

In [12]:
#Noisy samples are given the label -1.
dbscan.labels_

array([-1, -1, -1, -1, -1, -1,  0, -1, -1, -1, -1,  0, -1,  0,  0,  0,  0,
       -1,  0, -1,  1, -1,  0, -1,  0,  0,  0, -1,  0,  1, -1, -1, -1,  0,
        0,  0,  0,  0,  1, -1,  0, -1, -1,  0, -1,  0,  0,  0,  0,  0],
      dtype=int64)

In [13]:
clust=pd.DataFrame(dbscan.labels_,columns=['cluster'])

In [14]:
clust.head()

cluster
0       -1
1       -1
2       -1
3       -1
4       -1

In [16]:
crime_data_df = pd.concat([crime_data,clust],axis=1) 
crime_data_df.head(25)

Unnamed: 0  Murder  Assault  UrbanPop  Rape  cluster
0         Alabama    13.2      236        58  21.2       -1
1          Alaska    10.0      263        48  44.5       -1
2         Arizona     8.1      294        80  31.0       -1
3        Arkansas     8.8      190        50  19.5       -1
4      California     9.0      276        91  40.6       -1
5        Colorado     7.9      204        78  38.7       -1
6     Connecticut     3.3      110        77  11.1        0
7        Delaware     5.9      238        72  15.8       -1
8         Florida    15.4      335        80  31.9       -1
9         Georgia    17.4      211        60  25.8       -1
10         Hawaii     5.3       46        83  20.2       -1
11          Idaho     2.6      120        54  14.2        0
12       Illinois    10.4      249        83  24.0       -1
13        Indiana     7.2      113        65  21.0        0
14           Iowa     2.2       56        57  11.3        0
15         Kansas     6.0      115        66  18.0        0
16       Kentucky     9.7      109        52  16.3        0
17      Louisiana    15.4      249        66  22.2       -1
18          Maine     2.1       83        51   7.8        0
19       Maryland    11.3      300        67  27.8       -1
20  Massachusetts     4.4      149        85  16.3        1
21       Michigan    12.1      255        74  35.1       -1
22      Minnesota     2.7       72        66  14.9        0
23    Mississippi    16.1      259        44  17.1       -1
24       Missouri     9.0      178        70  28.2        0

In [17]:
#East West Airlines DBSCAN Clustering

In [18]:
EW_Airlines = pd.read_csv("EastWestAirlines.csv")
EW_Airlines.head()

ID#  Balance  Qual_miles  cc1_miles  cc2_miles  cc3_miles  Bonus_miles  \
0    1    28143           0          1          1          1          174   
1    2    19244           0          1          1          1          215   
2    3    41354           0          1          1          1         4123   
3    4    14776           0          1          1          1          500   
4    5    97752           0          4          1          1        43300   

   Bonus_trans  Flight_miles_12mo  Flight_trans_12  Days_since_enroll  Award?  
0            1                  0                0               7000       0  
1            2                  0                0               6968       0  
2            4                  0                0               7034       0  
3            1                  0                0               6952       0  
4           26               2077                4               6935       1

In [20]:
EW_Airlines1=EW_Airlines.iloc[:,1:]

In [21]:
array=EW_Airlines1.values
array

array([[28143,     0,     1, ...,     0,  7000,     0],
       [19244,     0,     1, ...,     0,  6968,     0],
       [41354,     0,     1, ...,     0,  7034,     0],
       ...,
       [73597,     0,     3, ...,     0,  1402,     1],
       [54899,     0,     1, ...,     1,  1401,     0],
       [ 3016,     0,     1, ...,     0,  1398,     0]], dtype=int64)

In [22]:
# Normalization function
from sklearn.preprocessing import StandardScaler
stscaler = StandardScaler().fit(array)
scaled_Airlines = stscaler.transform(array) 
scaled_Airlines

array([[-4.51140783e-01, -1.86298687e-01, -7.69578406e-01, ...,
        -3.62167870e-01,  1.39545434e+00, -7.66919299e-01],
       [-5.39456874e-01, -1.86298687e-01, -7.69578406e-01, ...,
        -3.62167870e-01,  1.37995704e+00, -7.66919299e-01],
       [-3.20031232e-01, -1.86298687e-01, -7.69578406e-01, ...,
        -3.62167870e-01,  1.41192021e+00, -7.66919299e-01],
       ...,
       [-4.29480975e-05, -1.86298687e-01,  6.83121167e-01, ...,
        -3.62167870e-01, -1.31560393e+00,  1.30391816e+00],
       [-1.85606976e-01, -1.86298687e-01, -7.69578406e-01, ...,
        -9.85033311e-02, -1.31608822e+00, -7.66919299e-01],
       [-7.00507951e-01, -1.86298687e-01, -7.69578406e-01, ...,
        -3.62167870e-01, -1.31754109e+00, -7.66919299e-01]])

In [30]:
dbscan_a = DBSCAN(eps=1, min_samples=5)
dbscan_a.fit(scaled_Airlines)

DBSCAN(algorithm='auto', eps=1, leaf_size=30, metric='euclidean',
       metric_params=None, min_samples=5, n_jobs=None, p=None)

In [31]:
#Noisy samples are given the label -1.
dbscan_a.labels_

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

In [32]:
clust_a=pd.DataFrame(dbscan_a.labels_,columns=['cluster'])

In [33]:
clust_a

cluster
0           0
1           0
2           0
3           0
4           1
...       ...
3994        1
3995        1
3996        1
3997        0
3998        0

[3999 rows x 1 columns]

In [34]:
Airlines_df = pd.concat([EW_Airlines,clust_a],axis=1) 
Airlines_df.head(25)

ID#  Balance  Qual_miles  cc1_miles  cc2_miles  cc3_miles  Bonus_miles  \
0     1    28143           0          1          1          1          174   
1     2    19244           0          1          1          1          215   
2     3    41354           0          1          1          1         4123   
3     4    14776           0          1          1          1          500   
4     5    97752           0          4          1          1        43300   
5     6    16420           0          1          1          1            0   
6     7    84914           0          3          1          1        27482   
7     8    20856           0          1          1          1         5250   
8     9   443003           0          3          2          1         1753   
9    10   104860           0          3          1          1        28426   
10   11    40091           0          2          1          1         7278   
11   12    96522           0          5          1          1        61105   
12   13    43382           0          2          1          1        11150   
13   14    43097           0          1          1          1         3258   
14   15    17648           0          1          1          1            0   
15   16    28495           0          4          1          1        49442   
16   17    51890           0          4          1          1        48963   
17   18    13958           0          1          1          1         4291   
18   19    91473           0          3          1          1        27408   
19   20    23354           0          3          1          1        10447   
20   21   120576           0          5          1          1        58831   
21   22   185681        2024          1          1          1        13300   
22   23    20584           0          1          1          1         3450   
23   24    66275           0          1          1          1         2533   
24   25   205651         500          1          1          1         4025   

    Bonus_trans  Flight_miles_12mo  Flight_trans_12  Days_since_enroll  \
0             1                  0                0               7000   
1             2                  0                0               6968   
2             4                  0                0               7034   
3             1                  0                0               6952   
4            26               2077                4               6935   
5             0                  0                0               6942   
6            25                  0                0               6994   
7             4                250                1               6938   
8            43               3850               12               6948   
9            28               1150                3               6931   
10           10                  0                0               6959   
11           19                  0                0               6924   
12           20                  0                0               6924   
13            6                  0                0               6918   
14            0                  0                0               6912   
15           15                  0                0               6912   
16           16                  0                0               6910   
17            5                  0                0               6905   
18           17                  0                0               6903   
19            5                  0                0               6896   
20           23                250                2               6896   
21           16               1800                9               6896   
22           11               3450               11               6884   
23           11                150                1               6884   
24           21                700                4               7932   

    Award?  cluster  
0        0        0  
1     